### ISSUE TITLE
Error while loading pyenv xontrib

### ISSUE THREAD

**Issue by dyuri** [dyuri/xontrib-pyenv#1]
See xonsh/xonsh#3610

```
pierre@kth ~ $ source-bash ~/Dev/env_xonsh/bin/activate                         
(env_xonsh) pierre@kth ~ $ $XONSH_DEBUG=1                                       
(env_xonsh) pierre@kth ~ $ $XONSH_SHOW_TRACEBACK = True                         
(env_xonsh) pierre@kth ~ $ xonsh                                                
Hello Pierre!
^Z
(env_xonsh) pierre@kth ~ $ xontrib load pyenv                                   
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22033, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 14147, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 15421, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22022, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22046, in _run_binary
    sug = suggest_commands(cmd0, env, builtins.aliases)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5293, in suggest_commands
    c = command_not_found(cmd)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5241, in command_not_found
    s = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/lib/command-not-found pyenv
; exit 0' returned non-zero exit status 2.
xonsh: To log full traceback to a file set: $XONSH_TRACEBACK_LOGFILE = <filename>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22033, in _run_binary
    p = self.cls(self.cmd, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 14147, in __init__
    self.proc = proc = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyenv\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 15421, in __init__
    proc = spec.run(pipeline_group=pipeline_group)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22022, in run
    p = self._run_binary(kwargs)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 22046, in _run_binary
    sug = suggest_commands(cmd0, env, builtins.aliases)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5293, in suggest_commands
    c = command_not_found(cmd)
  File "/usr/lib/python3/dist-packages/xonsh/__amalgam__.py", line 5241, in command_not_found
    s = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/usr/lib/command-not-found pyenv
; exit 0' returned non-zero exit status 2.
```

**Comment by dyuri** [comment]
While I cannot reproduce this here, the issue might be the `\n` at the end of the output of `$(which pyenv)`. Let's `strip()` it.

@paugier could you give a try with the latest code from master? If you confirm that it's working I'll release a new version.

**Comment by paugier** [comment]
Yes, I confirm that with the `strip()`, it works much better! Thanks!

**Comment by dyuri** [comment]
Great, version 1.0.4 released to PyPI.
